# Generated by Django 5.1.3 on 2024-11-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='ip_address',
            field=models.CharField(default='127.0.0.1', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='os_version',
            field=models.CharField(default='Windows 13', max_length=25),
            preserve_default=False,
        ),
    ]
