# Generated by Django 5.1.3 on 2024-11-11 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0003_rename_username_device_system_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='last_check_in',
            new_name='last_login',
        ),
    ]
