# Generated by Django 5.1.3 on 2024-11-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0005_device_username_alter_device_system_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('os_version', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('cpu_usage', models.FloatField()),
                ('memory_usage', models.FloatField()),
                ('disk_usage', models.FloatField()),
                ('activity_log', models.TextField()),
                ('running_processes', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
