# Generated by Django 5.1.3 on 2024-11-11 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0006_systemactivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemactivity',
            name='cpu_usage',
        ),
        migrations.RemoveField(
            model_name='systemactivity',
            name='disk_usage',
        ),
        migrations.RemoveField(
            model_name='systemactivity',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='systemactivity',
            name='memory_usage',
        ),
        migrations.RemoveField(
            model_name='systemactivity',
            name='os_version',
        ),
        migrations.RemoveField(
            model_name='systemactivity',
            name='system_name',
        ),
        migrations.RemoveField(
            model_name='systemactivity',
            name='username',
        ),
        migrations.AddField(
            model_name='systemactivity',
            name='device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Devices.device'),
            preserve_default=False,
        ),
    ]
