# Generated by Django 5.1.3 on 2024-11-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0007_remove_systemactivity_cpu_usage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='system_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
