# Generated by Django 5.1.3 on 2024-11-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0009_alter_systemactivity_running_processes'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemactivity',
            name='color',
            field=models.CharField(default='black', max_length=10),
            preserve_default=False,
        ),
    ]
