# Generated by Django 5.1.3 on 2024-11-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0010_systemactivity_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemactivity',
            name='color',
            field=models.CharField(default='gray', max_length=10),
        ),
    ]
